name: Android camera mds

on:
  release:
    types: [published]
  pull_request:
    types: [opened]
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for manually triggering'
        required: false
        default: 'Triggered for Updates'
        type: string
  push:
    branches:
      - '!release-branch'
      - release*
      - master
      - 1.*
      - develop*
      - MOSIP*

jobs:
  build-camera-mds:
    uses: mosip/kattu/.github/workflows/npm-andriod-build.yml@master
    with:
      SERVICE_LOCATION: 'MockAndroidSBI'
      ANDROID_LOCATION: '../MockAndroidSBI'
      BUILD_ARTIFACT: 'camera-mds'
      GRADLEW_ARGS: 'assembleDebug'
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
